# Generated by Django 4.2.3 on 2023-07-15 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auction'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='imageUrl',
            field=models.URLField(blank=True),
        ),
    ]
