# Generated by Django 4.2.3 on 2023-07-16 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_remove_watchlist_auction_watchlist_auction'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='category',
            field=models.TextField(default='Default Category', max_length=64),
        ),
    ]
