# Generated by Django 4.2.3 on 2023-07-16 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_alter_auction_category_delete_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('food', 'Food'), ('fashion', ' Fashion'), ('personalCare', 'Personal Care'), ('software', 'Software'), ('home', 'Home and Kitchen'), ('electronics', 'Electronics'), ('book', 'Book'), ('others', 'Others')], max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='auction',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auctions.category'),
        ),
    ]
