# Generated by Django 4.2.3 on 2023-07-16 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_category_alter_auction_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('food', 'Food'), ('fashion', ' Fashion'), ('personalCare', 'Personal Care'), ('software', 'Software'), ('home', 'Home and Kitchen'), ('electronics', 'Electronics'), ('book', 'Book'), ('others', 'Others'), ('Default Category', 'Default Category')], max_length=100),
        ),
    ]
