# Generated by Django 4.2.3 on 2023-07-17 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_alter_auction_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='category',
            field=models.ForeignKey(null='True', on_delete=django.db.models.deletion.CASCADE, to='auctions.category'),
        ),
    ]
