# Generated by Django 4.2.3 on 2023-07-17 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_alter_auction_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='category',
            field=models.CharField(choices=[('food', 'Food'), ('fashion', ' Fashion'), ('personalCare', 'Personal Care'), ('software', 'Software'), ('home', 'Home and Kitchen'), ('electronics', 'Electronics'), ('book', 'Book'), ('others', 'Others'), ('Default Category', 'Default Category')], default='default', max_length=100),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
