# Generated by Django 4.2.3 on 2023-07-17 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0018_bid_isaccepted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='isAccepted',
        ),
    ]
